export interface SaudiCity {
  nameAr: string;
  nameEn: string;
}

const unsortedCities: SaudiCity[] = [
  { nameAr: "الرياض", nameEn: "Riyadh" },
  { nameAr: "جدة", nameEn: "Jeddah" },
  { nameAr: "مكة المكرمة", nameEn: "Makkah" },
  { nameAr: "المدينة المنورة", nameEn: "Madinah" },
  { nameAr: "الدمام", nameEn: "Dammam" },
  { nameAr: "الخبر", nameEn: "Khobar" },
  { nameAr: "الظهران", nameEn: "Dhahran" },
  { nameAr: "الطائف", nameEn: "Taif" },
  { nameAr: "تبوك", nameEn: "Tabuk" },
  { nameAr: "بريدة", nameEn: "Buraidah" },
  { nameAr: "خميس مشيط", nameEn: "Khamis Mushait" },
  { nameAr: "أبها", nameEn: "Abha" },
  { nameAr: "القطيف", nameEn: "Qatif" },
  { nameAr: "الجبيل", nameEn: "Jubail" },
  { nameAr: "حائل", nameEn: "Hail" },
  { nameAr: "نجران", nameEn: "Najran" },
  { nameAr: "جازان", nameEn: "Jazan" },
  { nameAr: "ينبع", nameEn: "Yanbu" },
  { nameAr: "الأحساء", nameEn: "Al-Ahsa" },
  { nameAr: "القصيم", nameEn: "Qassim" },
  { nameAr: "الخرج", nameEn: "Al-Kharj" },
  { nameAr: "عرعر", nameEn: "Arar" },
  { nameAr: "سكاكا", nameEn: "Sakaka" },
  { nameAr: "الباحة", nameEn: "Al-Baha" },
  { nameAr: "بيشة", nameEn: "Bisha" },
  { nameAr: "الدوادمي", nameEn: "Dawadmi" },
  { nameAr: "المجمعة", nameEn: "Al-Majma'ah" },
  { nameAr: "الزلفي", nameEn: "Zulfi" },
  { nameAr: "شقراء", nameEn: "Shaqra" },
  { nameAr: "عنيزة", nameEn: "Unaizah" },
  { nameAr: "الرس", nameEn: "Ar-Rass" },
  { nameAr: "المذنب", nameEn: "Al-Mithnab" },
  { nameAr: "البكيرية", nameEn: "Al-Bukayriyah" },
  { nameAr: "رفحاء", nameEn: "Rafha" },
  { nameAr: "طريف", nameEn: "Turaif" },
  { nameAr: "القريات", nameEn: "Qurayyat" },
  { nameAr: "دومة الجندل", nameEn: "Dumat Al-Jandal" },
  { nameAr: "وادي الدواسر", nameEn: "Wadi ad-Dawasir" },
  { nameAr: "السليل", nameEn: "As-Sulayyil" },
  { nameAr: "الأفلاج", nameEn: "Al-Aflaj" },
  { nameAr: "حوطة بني تميم", nameEn: "Howtat Bani Tamim" },
  { nameAr: "المزاحمية", nameEn: "Al-Muzahmiyya" },
  { nameAr: "ضرما", nameEn: "Dirma" },
  { nameAr: "رماح", nameEn: "Rumah" },
  { nameAr: "ثادق", nameEn: "Thadiq" },
  { nameAr: "حريملاء", nameEn: "Huraymila" },
  { nameAr: "عفيف", nameEn: "Afif" },
  { nameAr: "ساجر", nameEn: "Sajir" },
  { nameAr: "القويعية", nameEn: "Al-Quwai'iyah" },
  { nameAr: "رابغ", nameEn: "Rabigh" },
  { nameAr: "الليث", nameEn: "Al-Lith" },
  { nameAr: "القنفذة", nameEn: "Al-Qunfudhah" },
  { nameAr: "الكامل", nameEn: "Al-Kamil" },
  { nameAr: "خليص", nameEn: "Khulais" },
  { nameAr: "المويه", nameEn: "Al-Muwayh" },
  { nameAr: "تربة", nameEn: "Turbah" },
  { nameAr: "الخرمة", nameEn: "Al-Khurma" },
  { nameAr: "رنية", nameEn: "Ranyah" },
  { nameAr: "محايل عسير", nameEn: "Muhayil Asir" },
  { nameAr: "النماص", nameEn: "An-Namas" },
  { nameAr: "تنومة", nameEn: "Tanumah" },
  { nameAr: "سراة عبيدة", nameEn: "Sarat Abidah" },
  { nameAr: "رجال ألمع", nameEn: "Rijal Alma" },
  { nameAr: "ظهران الجنوب", nameEn: "Dhahran Al-Janub" },
  { nameAr: "بلقرن", nameEn: "Balqarn" },
  { nameAr: "المجاردة", nameEn: "Al-Majardah" },
  { nameAr: "البرك", nameEn: "Al-Birk" },
  { nameAr: "أحد المسارحة", nameEn: "Ahad Al-Masarihah" },
  { nameAr: "صبيا", nameEn: "Sabya" },
  { nameAr: "أبو عريش", nameEn: "Abu Arish" },
  { nameAr: "صامطة", nameEn: "Samtah" },
  { nameAr: "فيفا", nameEn: "Fayfa" },
  { nameAr: "الدرب", nameEn: "Ad-Darb" },
  { nameAr: "العارضة", nameEn: "Al-Aridah" },
  { nameAr: "الحرث", nameEn: "Al-Harith" },
  { nameAr: "شرورة", nameEn: "Sharurah" },
  { nameAr: "حبونا", nameEn: "Hubuna" },
  { nameAr: "بدر الجنوب", nameEn: "Badr Al-Janub" },
  { nameAr: "يدمة", nameEn: "Yadamah" },
  { nameAr: "ثار", nameEn: "Thar" },
  { nameAr: "الحناكية", nameEn: "Al-Hanakiyah" },
  { nameAr: "العلا", nameEn: "Al-Ula" },
  { nameAr: "مهد الذهب", nameEn: "Mahd adh-Dhahab" },
  { nameAr: "بدر", nameEn: "Badr" },
  { nameAr: "خيبر", nameEn: "Khaybar" },
  { nameAr: "وادي الفرع", nameEn: "Wadi Al-Far'" },
  { nameAr: "ضباء", nameEn: "Duba" },
  { nameAr: "تيماء", nameEn: "Tayma" },
  { nameAr: "أملج", nameEn: "Umluj" },
  { nameAr: "الوجه", nameEn: "Al-Wajh" },
  { nameAr: "حقل", nameEn: "Haql" },
  { nameAr: "البدع", nameEn: "Al-Bada'" },
  { nameAr: "رأس تنورة", nameEn: "Ras Tanura" },
  { nameAr: "بقيق", nameEn: "Buqayq" },
  { nameAr: "العيون", nameEn: "Al-Oyun" },
  { nameAr: "النعيرية", nameEn: "An-Nu'ayriyah" },
  { nameAr: "قرية العليا", nameEn: "Qaryat Al-Ulya" },
  { nameAr: "حفر الباطن", nameEn: "Hafar Al-Batin" },
  { nameAr: "الخفجي", nameEn: "Khafji" },
  { nameAr: "المندق", nameEn: "Al-Mandaq" },
  { nameAr: "قلوة", nameEn: "Qilwah" },
  { nameAr: "العقيق", nameEn: "Al-Aqiq" },
  { nameAr: "بلجرشي", nameEn: "Baljurashi" },
  { nameAr: "غامد الزناد", nameEn: "Ghamid Az-Zinad" },
  { nameAr: "الجموم", nameEn: "Al-Jumum" },
  { nameAr: "الشرائع", nameEn: "Ash-Sharai" },
  { nameAr: "العزيزية", nameEn: "Al-Aziziyah" },
  { nameAr: "الجعرانة", nameEn: "Al-Ji'ranah" },
  { nameAr: "الكر", nameEn: "Al-Kar" },
  { nameAr: "ميسان", nameEn: "Maysan" },
  { nameAr: "بحرة", nameEn: "Bahrah" },
  { nameAr: "الحرة", nameEn: "Al-Harrah" },
  { nameAr: "أضم", nameEn: "Adham" },
  { nameAr: "العرضيات", nameEn: "Al-Ardiyat" },
  { nameAr: "القرى", nameEn: "Al-Qura" },
  { nameAr: "الموية", nameEn: "Al-Muwayah" },
  { nameAr: "الحائط", nameEn: "Al-Ha'it" },
  { nameAr: "الغزالة", nameEn: "Al-Ghazalah" },
  { nameAr: "الشنان", nameEn: "Ash-Shinan" },
  { nameAr: "موقق", nameEn: "Mawqaq" },
  { nameAr: "بقعاء", nameEn: "Buqa'a" },
  { nameAr: "الشملي", nameEn: "Ash-Shamli" },
  { nameAr: "السليمي", nameEn: "As-Sulaymi" },
  { nameAr: "تربة حائل", nameEn: "Turbat Hail" },
  { nameAr: "سميراء", nameEn: "Sumayra" },
  { nameAr: "الحليفة", nameEn: "Al-Hulayfah" },
  { nameAr: "جبة", nameEn: "Jubbah" },
  { nameAr: "الروضة", nameEn: "Ar-Rawdah" },
  { nameAr: "الشيحية", nameEn: "Ash-Shiyhiyah" },
  { nameAr: "الخطة", nameEn: "Al-Khuttah" },
  { nameAr: "قفار", nameEn: "Qifar" },
  { nameAr: "النبهانية", nameEn: "An-Nabhaniyah" },
  { nameAr: "عيون الجواء", nameEn: "Uyun Al-Jiwa" },
  { nameAr: "الأسياح", nameEn: "Al-Asyah" },
  { nameAr: "البدائع", nameEn: "Al-Badai" },
  { nameAr: "رياض الخبراء", nameEn: "Riyad Al-Khabra" },
  { nameAr: "الشماسية", nameEn: "Ash-Shamasiyah" },
  { nameAr: "عقلة الصقور", nameEn: "Uqlat As-Suqur" },
  { nameAr: "ضرية", nameEn: "Dariyah" },
  { nameAr: "دخنة", nameEn: "Dukhnah" },
  { nameAr: "الخبراء", nameEn: "Al-Khabra" },
  { nameAr: "الفوارة", nameEn: "Al-Fawwarah" },
  { nameAr: "البطين", nameEn: "Al-Butayn" },
  { nameAr: "المطيوي", nameEn: "Al-Mutaywi" },
  { nameAr: "الهلالية", nameEn: "Al-Hilaliyah" },
  { nameAr: "صفينة", nameEn: "Sufaynah" },
  { nameAr: "صلبوخ", nameEn: "Salbukh" },
  { nameAr: "العيينة", nameEn: "Al-Uyaynah" },
  { nameAr: "الجبيلة", nameEn: "Al-Jubaylah" },
  { nameAr: "العمارية", nameEn: "Al-Ammariyah" },
  { nameAr: "الحائر", nameEn: "Al-Ha'ir" },
  { nameAr: "بنبان", nameEn: "Banban" },
  { nameAr: "الغاط", nameEn: "Al-Ghat" },
  { nameAr: "مرات", nameEn: "Marat" },
  { nameAr: "حرمة", nameEn: "Harmah" },
  { nameAr: "تمير", nameEn: "Tumair" },
  { nameAr: "جلاجل", nameEn: "Jalajil" },
  { nameAr: "ملهم", nameEn: "Malham" },
  { nameAr: "الحريق", nameEn: "Al-Hariq" },
  { nameAr: "نعجان", nameEn: "Na'jan" },
  { nameAr: "الدلم", nameEn: "Ad-Dilam" },
  { nameAr: "السيح", nameEn: "As-Sayh" },
  { nameAr: "الهياثم", nameEn: "Al-Hayathem" },
  { nameAr: "اليمامة", nameEn: "Al-Yamamah" },
  { nameAr: "ليلى", nameEn: "Layla" },
  { nameAr: "البديع", nameEn: "Al-Badi" },
  { nameAr: "نفي", nameEn: "Nafi" },
  { nameAr: "هجرة تمرة", nameEn: "Hijrat Tamra" },
  { nameAr: "الرين", nameEn: "Ar-Rayn" },
  { nameAr: "البجادية", nameEn: "Al-Bijadiyah" },
  { nameAr: "الشعراء", nameEn: "Ash-Sha'ra" },
  { nameAr: "مشرفة", nameEn: "Mushrifah" },
  { nameAr: "نفى", nameEn: "Nafa" },
  { nameAr: "السر", nameEn: "As-Sirr" },
  { nameAr: "الجفر", nameEn: "Al-Jafr" },
  { nameAr: "الحوطة", nameEn: "Al-Hawtah" },
  { nameAr: "الطرف", nameEn: "At-Taraf" },
  { nameAr: "العقير", nameEn: "Al-Uqayr" },
  { nameAr: "العمران", nameEn: "Al-Omran" },
  { nameAr: "الجشة", nameEn: "Al-Jishah" },
  { nameAr: "المبرز", nameEn: "Al-Mubarraz" },
  { nameAr: "الهفوف", nameEn: "Al-Hofuf" },
  { nameAr: "العيون", nameEn: "Al-Uyun" },
  { nameAr: "الشهارين", nameEn: "Ash-Shaharin" },
  { nameAr: "جوادا", nameEn: "Jawatha" },
  { nameAr: "سيهات", nameEn: "Sayhat" },
  { nameAr: "عوامية", nameEn: "Awamiyah" },
  { nameAr: "صفوى", nameEn: "Safwa" },
  { nameAr: "تاروت", nameEn: "Tarut" },
  { nameAr: "الدغيمية", nameEn: "Ad-Dughaimiyyah" },
  { nameAr: "العديد", nameEn: "Al-Adid" },
  { nameAr: "الملاحة", nameEn: "Al-Malahah" },
  { nameAr: "أم الساهك", nameEn: "Umm As-Sahik" },
  { nameAr: "الدريدي", nameEn: "Ad-Duraidi" },
  { nameAr: "الحنابجة", nameEn: "Al-Hanabjah" },
  { nameAr: "الجرذاوية", nameEn: "Al-Jardhawiyyah" },
  { nameAr: "الوسيطاء", nameEn: "Al-Wusayta" },
  { nameAr: "المرقاب", nameEn: "Al-Murqab" },
  { nameAr: "الناصرية", nameEn: "An-Nasiriyah" },
  { nameAr: "السكاك", nameEn: "As-Sikkak" },
  { nameAr: "القارة", nameEn: "Al-Qara" },
  { nameAr: "طبرجل", nameEn: "Tabarjal" },
  { nameAr: "صوير", nameEn: "Suwayr" },
  { nameAr: "العويقيلة", nameEn: "Al-Uwayqilah" },
  { nameAr: "عين دار", nameEn: "Ain Dar" },
  { nameAr: "العضيلية", nameEn: "Al-Udayliyyah" },
  { nameAr: "عين الدار", nameEn: "Ayn ad-Dar" },
  { nameAr: "أحد رفيدة", nameEn: "Ahad Rufaydah" },
  { nameAr: "الحرجة", nameEn: "Al-Harjah" },
  { nameAr: "المضة", nameEn: "Al-Madd'ah" },
  { nameAr: "قنا", nameEn: "Qana" },
  { nameAr: "طريب", nameEn: "Turayb" },
  { nameAr: "البشائر", nameEn: "Al-Basha'ir" },
  { nameAr: "تثليث", nameEn: "Tathlith" },
  { nameAr: "الواديين", nameEn: "Al-Wadiyayn" },
  { nameAr: "مربة", nameEn: "Marbah" },
  { nameAr: "الفرشة", nameEn: "Al-Farshah" },
  { nameAr: "عبس", nameEn: "Abs" },
  { nameAr: "الحقو", nameEn: "Al-Haqw" },
  { nameAr: "بيش", nameEn: "Baysh" },
  { nameAr: "الطوال", nameEn: "At-Tuwal" },
  { nameAr: "هروب", nameEn: "Harub" },
  { nameAr: "الريث", nameEn: "Ar-Rayth" },
  { nameAr: "فرسان", nameEn: "Farasan" },
  { nameAr: "القحمة", nameEn: "Al-Qahmah" },
  { nameAr: "الموسم", nameEn: "Al-Mawsim" },
  { nameAr: "خباش", nameEn: "Khubash" },
  { nameAr: "الشقيق", nameEn: "Ash-Shiqiq" },
  { nameAr: "ضمد", nameEn: "Damad" },
  { nameAr: "الخوبة", nameEn: "Al-Khawbah" },
  { nameAr: "الدائر", nameEn: "Ad-Da'ir" },
  { nameAr: "العيدابي", nameEn: "Al-Aydabi" },
  { nameAr: "المسارحة", nameEn: "Al-Masarihah" },
  { nameAr: "أحد بني زيد", nameEn: "Ahad Bani Zayd" },
  { nameAr: "غزالة", nameEn: "Ghazalah" },
  { nameAr: "الحجرة", nameEn: "Al-Hajrah" },
  { nameAr: "القرن", nameEn: "Al-Qarn" },
  { nameAr: "الساحل", nameEn: "As-Sahil" },
  { nameAr: "غميقة", nameEn: "Ghumaiqah" },
  { nameAr: "الحازمي", nameEn: "Al-Hazmi" },
  { nameAr: "المظيلف", nameEn: "Al-Muzaylif" },
  { nameAr: "الحوية", nameEn: "Al-Hawiyah" },
  { nameAr: "السيل الكبير", nameEn: "As-Sayl Al-Kabir" },
  { nameAr: "بني سعد", nameEn: "Bani Sa'd" },
  { nameAr: "ثقيف", nameEn: "Thaqif" },
  { nameAr: "العرفاء", nameEn: "Al-Arfa" },
  { nameAr: "الشفا", nameEn: "Ash-Shafa" },
  { nameAr: "الهدا", nameEn: "Al-Hada" },
  { nameAr: "البهيتة", nameEn: "Al-Buhaytah" },
  { nameAr: "نخال", nameEn: "Nakhal" },
  { nameAr: "عشيرة", nameEn: "Ushayrah" },
  { nameAr: "الصالحية", nameEn: "As-Salihiyyah" },
  { nameAr: "الفويلق", nameEn: "Al-Fuwayliq" },
  { nameAr: "البرابر", nameEn: "Al-Barabir" },
  { nameAr: "دارين", nameEn: "Darin" },
  { nameAr: "الجش", nameEn: "Al-Jish" },
  { nameAr: "حزم الجلاميد", nameEn: "Hazm Al-Jalamid" },
  { nameAr: "لينة", nameEn: "Linah" },
  { nameAr: "الشحمة", nameEn: "Ash-Shahmah" },
  { nameAr: "الكهفة", nameEn: "Al-Kahfah" },
  { nameAr: "نجود", nameEn: "Nujud" },
  { nameAr: "الرقعي", nameEn: "Ar-Ruq'i" },
  { nameAr: "الصرار", nameEn: "As-Sarrar" },
  { nameAr: "أم رضمة", nameEn: "Umm Radmah" },
  { nameAr: "عين بن فهيد", nameEn: "Ayn Bin Fuhayd" },
  { nameAr: "الثنية", nameEn: "Ath-Thuniyah" },
  { nameAr: "القيصومة", nameEn: "Al-Qaysumah" },
  { nameAr: "الحماد", nameEn: "Al-Hammad" },
  { nameAr: "الزهراء", nameEn: "Az-Zahra" },
  { nameAr: "سدير", nameEn: "Sudayr" },
  { nameAr: "روضة سدير", nameEn: "Rawdat Sudayr" },
  { nameAr: "حوطة سدير", nameEn: "Hawtat Sudayr" },
  { nameAr: "عودة سدير", nameEn: "Awdat Sudayr" },
  { nameAr: "الدرعية", nameEn: "Diriyah" },
  { nameAr: "الملز", nameEn: "Al-Malaz" },
  { nameAr: "الشميسي", nameEn: "Ash-Shimaysi" },
  { nameAr: "النسيم", nameEn: "An-Nasim" },
  { nameAr: "الورود", nameEn: "Al-Wurud" },
  { nameAr: "السويدي", nameEn: "As-Suwaydi" },
  { nameAr: "العليا", nameEn: "Al-Olaya" },
  { nameAr: "النخيل", nameEn: "An-Nakhil" },
  { nameAr: "الربوة", nameEn: "Ar-Rabwah" },
  { nameAr: "السلام", nameEn: "As-Salam" },
  { nameAr: "الروابي", nameEn: "Ar-Rawabi" },
  { nameAr: "الفلاح", nameEn: "Al-Falah" },
  { nameAr: "العزيزية", nameEn: "Al-Aziziyah" },
  { nameAr: "الحمراء", nameEn: "Al-Hamra" },
  { nameAr: "الصحافة", nameEn: "As-Sahafah" },
  { nameAr: "الملقا", nameEn: "Al-Malqa" },
  { nameAr: "الياسمين", nameEn: "Al-Yasmin" },
  { nameAr: "النرجس", nameEn: "An-Narjis" },
  { nameAr: "العارض", nameEn: "Al-Arid" },
  { nameAr: "خشم العان", nameEn: "Khashm Al-An" },
  { nameAr: "البطحاء", nameEn: "Al-Batha" },
  { nameAr: "الفاخرية", nameEn: "Al-Fakhriyah" },
  { nameAr: "السلي", nameEn: "As-Sulay" },
  { nameAr: "الشفاء", nameEn: "Ash-Shifa" },
  { nameAr: "المرسلات", nameEn: "Al-Mursalat" },
  { nameAr: "الإسكان", nameEn: "Al-Iskan" },
  { nameAr: "نمار", nameEn: "Namar" },
  { nameAr: "الصفراء", nameEn: "As-Safra" },
  { nameAr: "بني مالك", nameEn: "Bani Malik" },
  { nameAr: "الداير", nameEn: "Ad-Dayir" },
];

export const saudiCities: SaudiCity[] = unsortedCities.sort((a, b) => 
  a.nameAr.localeCompare(b.nameAr, 'ar')
);

export const cityNamesAr = saudiCities.map(city => city.nameAr);
