export interface SaudiCity {
  nameAr: string;
  nameEn: string;
}

export const saudiCities: SaudiCity[] = [
  { nameAr: "الرياض", nameEn: "Riyadh" },
  { nameAr: "جدة", nameEn: "Jeddah" },
  { nameAr: "مكة المكرمة", nameEn: "Makkah" },
  { nameAr: "المدينة المنورة", nameEn: "Madinah" },
  { nameAr: "الدمام", nameEn: "Dammam" },
  { nameAr: "الخبر", nameEn: "Khobar" },
  { nameAr: "الظهران", nameEn: "Dhahran" },
  { nameAr: "الطائف", nameEn: "Taif" },
  { nameAr: "تبوك", nameEn: "Tabuk" },
  { nameAr: "بريدة", nameEn: "Buraidah" },
  { nameAr: "خميس مشيط", nameEn: "Khamis Mushait" },
  { nameAr: "أبها", nameEn: "Abha" },
  { nameAr: "القطيف", nameEn: "Qatif" },
  { nameAr: "الجبيل", nameEn: "Jubail" },
  { nameAr: "حائل", nameEn: "Hail" },
  { nameAr: "نجران", nameEn: "Najran" },
  { nameAr: "جازان", nameEn: "Jazan" },
  { nameAr: "ينبع", nameEn: "Yanbu" },
  { nameAr: "الأحساء", nameEn: "Al-Ahsa" },
  { nameAr: "القصيم", nameEn: "Qassim" },
  { nameAr: "الخرج", nameEn: "Al-Kharj" },
  { nameAr: "عرعر", nameEn: "Arar" },
  { nameAr: "سكاكا", nameEn: "Sakaka" },
  { nameAr: "الباحة", nameEn: "Al-Baha" },
  { nameAr: "بيشة", nameEn: "Bisha" },
  { nameAr: "الدوادمي", nameEn: "Dawadmi" },
  { nameAr: "المجمعة", nameEn: "Al-Majma'ah" },
  { nameAr: "الزلفي", nameEn: "Zulfi" },
  { nameAr: "شقراء", nameEn: "Shaqra" },
  { nameAr: "عنيزة", nameEn: "Unaizah" },
  { nameAr: "الرس", nameEn: "Ar-Rass" },
  { nameAr: "المذنب", nameEn: "Al-Mithnab" },
  { nameAr: "البكيرية", nameEn: "Al-Bukayriyah" },
  { nameAr: "رفحاء", nameEn: "Rafha" },
  { nameAr: "طريف", nameEn: "Turaif" },
  { nameAr: "القريات", nameEn: "Qurayyat" },
  { nameAr: "دومة الجندل", nameEn: "Dumat Al-Jandal" },
  { nameAr: "وادي الدواسر", nameEn: "Wadi ad-Dawasir" },
  { nameAr: "السليل", nameEn: "As-Sulayyil" },
  { nameAr: "الأفلاج", nameEn: "Al-Aflaj" },
  { nameAr: "حوطة بني تميم", nameEn: "Howtat Bani Tamim" },
  { nameAr: "المزاحمية", nameEn: "Al-Muzahmiyya" },
  { nameAr: "ضرما", nameEn: "Dirma" },
  { nameAr: "رماح", nameEn: "Rumah" },
  { nameAr: "ثادق", nameEn: "Thadiq" },
  { nameAr: "حريملاء", nameEn: "Huraymila" },
  { nameAr: "عفيف", nameEn: "Afif" },
  { nameAr: "ساجر", nameEn: "Sajir" },
  { nameAr: "القويعية", nameEn: "Al-Quwai'iyah" },
  { nameAr: "رابغ", nameEn: "Rabigh" },
  { nameAr: "الليث", nameEn: "Al-Lith" },
  { nameAr: "القنفذة", nameEn: "Al-Qunfudhah" },
  { nameAr: "الكامل", nameEn: "Al-Kamil" },
  { nameAr: "خليص", nameEn: "Khulais" },
  { nameAr: "المويه", nameEn: "Al-Muwayh" },
  { nameAr: "تربة", nameEn: "Turbah" },
  { nameAr: "الخرمة", nameEn: "Al-Khurma" },
  { nameAr: "رنية", nameEn: "Ranyah" },
  { nameAr: "محايل عسير", nameEn: "Muhayil Asir" },
  { nameAr: "النماص", nameEn: "An-Namas" },
  { nameAr: "تنومة", nameEn: "Tanumah" },
  { nameAr: "سراة عبيدة", nameEn: "Sarat Abidah" },
  { nameAr: "رجال ألمع", nameEn: "Rijal Alma" },
  { nameAr: "ظهران الجنوب", nameEn: "Dhahran Al-Janub" },
  { nameAr: "بلقرن", nameEn: "Balqarn" },
  { nameAr: "المجاردة", nameEn: "Al-Majardah" },
  { nameAr: "البرك", nameEn: "Al-Birk" },
  { nameAr: "أحد المسارحة", nameEn: "Ahad Al-Masarihah" },
  { nameAr: "صبيا", nameEn: "Sabya" },
  { nameAr: "أبو عريش", nameEn: "Abu Arish" },
  { nameAr: "صامطة", nameEn: "Samtah" },
  { nameAr: "فيفا", nameEn: "Fayfa" },
  { nameAr: "الدرب", nameEn: "Ad-Darb" },
  { nameAr: "العارضة", nameEn: "Al-Aridah" },
  { nameAr: "الحرث", nameEn: "Al-Harith" },
  { nameAr: "شرورة", nameEn: "Sharurah" },
  { nameAr: "حبونا", nameEn: "Hubuna" },
  { nameAr: "بدر الجنوب", nameEn: "Badr Al-Janub" },
  { nameAr: "يدمة", nameEn: "Yadamah" },
  { nameAr: "ثار", nameEn: "Thar" },
  { nameAr: "الحناكية", nameEn: "Al-Hanakiyah" },
  { nameAr: "العلا", nameEn: "Al-Ula" },
  { nameAr: "مهد الذهب", nameEn: "Mahd adh-Dhahab" },
  { nameAr: "بدر", nameEn: "Badr" },
  { nameAr: "خيبر", nameEn: "Khaybar" },
  { nameAr: "وادي الفرع", nameEn: "Wadi Al-Far'" },
  { nameAr: "ضباء", nameEn: "Duba" },
  { nameAr: "تيماء", nameEn: "Tayma" },
  { nameAr: "أملج", nameEn: "Umluj" },
  { nameAr: "الوجه", nameEn: "Al-Wajh" },
  { nameAr: "حقل", nameEn: "Haql" },
  { nameAr: "البدع", nameEn: "Al-Bada'" },
  { nameAr: "رأس تنورة", nameEn: "Ras Tanura" },
  { nameAr: "بقيق", nameEn: "Buqayq" },
  { nameAr: "العيون", nameEn: "Al-Oyun" },
  { nameAr: "النعيرية", nameEn: "An-Nu'ayriyah" },
  { nameAr: "قرية العليا", nameEn: "Qaryat Al-Ulya" },
  { nameAr: "حفر الباطن", nameEn: "Hafar Al-Batin" },
  { nameAr: "الخفجي", nameEn: "Khafji" },
  { nameAr: "المندق", nameEn: "Al-Mandaq" },
  { nameAr: "قلوة", nameEn: "Qilwah" },
  { nameAr: "العقيق", nameEn: "Al-Aqiq" },
  { nameAr: "بلجرشي", nameEn: "Baljurashi" },
  { nameAr: "غامد الزناد", nameEn: "Ghamid Az-Zinad" },
];

export const cityNamesAr = saudiCities.map(city => city.nameAr);
